#include "rk/Settings.hpp"
namespace rk {
const std::vector<Field>& settingsSchema() {
    static const std::vector<Field> fields{
        {"General.SchemaVersion", std::int64_t{1}, 1, 1, {}},
        {"General.Enabled", true, 0, 2, {}},
        {"General.SafeMode", false, 0, 2, {}},
        {"General.Presentation", Choice{"Auto"}, 0, 2, {"Auto","NativeD3D11","ProxyD3D12"}},
        {"General.ConflictPolicy", Choice{"DisableThisPlugin"}, 0, 2, {"DisableThisPlugin"}},
        {"General.LogLevel", Choice{"Info"}, 0, 2, {"Trace","Debug","Info","Warn","Error"}},
        {"Adapter.Selection", Choice{"Renderer"}, 0, 2, {"Renderer"}},
        {"Adapter.AllowCrossAdapter", false, 0, 2, {}},
        {"Upscaling.Provider", Choice{"Auto"}, 0, 2, {"Auto","Native","DLSS","FSR","XeSS"}},
        {"Upscaling.Quality", Choice{"Quality"}, 0, 2, {"NativeAA","Quality","Balanced","Performance","UltraPerformance"}},
        {"Upscaling.ModelPreset", Text{"Auto"}, 0, 2, {}},
        {"Upscaling.AutoExposure", true, 0, 2, {}},
        {"Upscaling.Sharpening", true, 0, 2, {}},
        {"Upscaling.Sharpness", double{0.30}, 0, 1, {}},
        {"Upscaling.MipBiasMode", Choice{"Auto"}, 0, 2, {"Auto","Manual"}},
        {"Upscaling.ManualMipBias", double{0.0}, -8, 8, {}},
        {"Upscaling.ManualRenderScale", double{0.0}, 0, 1, {}},
        {"FrameGeneration.Enabled", false, 0, 2, {}},
        {"FrameGeneration.Provider", Choice{"Auto"}, 0, 2, {"Auto","DLSS","FSR","XeSS"}},
        {"FrameGeneration.ExtraGeneratedFrames", std::int64_t{1}, 1, 16, {}},
        {"FrameGeneration.DynamicFrameCount", false, 0, 2, {}},
        {"FrameGeneration.TargetDisplayedFPS", std::int64_t{0}, 0, 1000, {}},
        {"FrameGeneration.LatencyMode", Choice{"Auto"}, 0, 2, {"Auto","Off","Reflex","XeLL"}},
        {"FrameGeneration.UIComposition", Choice{"Auto"}, 0, 2, {"Auto","NativePlane","ProviderDefault","DifferenceMaskExperimental"}},
        {"NeuralRendering.Enabled", false, 0, 2, {}},
        {"NeuralRendering.Backend", Choice{"Auto"}, 0, 2, {"Auto","Direct","Streamline"}},
        {"NeuralRendering.Position", Choice{"BeforeSR"}, 0, 2, {"BeforeSR","AfterSR"}},
        {"NeuralRendering.Preset", Text{"Auto"}, 0, 2, {}},
        {"NeuralRendering.Style", std::int64_t{0}, 0, 255, {}},
        {"NeuralRendering.Intensity", double{1.0}, 0, 2, {}},
        {"NeuralRendering.LocalToneStrength", double{1.0}, 0, 2, {}},
        {"NeuralRendering.LocalStructureStrength", double{1.0}, 0, 2, {}},
        {"NeuralRendering.SkinStructureStrength", Text{"Auto"}, 0, 2, {}},
        {"NeuralRendering.UseAutoMask", false, 0, 2, {}},
        {"NeuralRendering.PassCount", std::int64_t{1}, 1, 8, {}},
        {"NeuralRendering.InputResolutionScale", double{1.0}, 0.125, 1, {}},
        {"NeuralRendering.NativeUICorrection", false, 0, 2, {}},
        {"NeuralRendering.Resolve", Choice{"Auto"}, 0, 2, {"Auto","Residual","Ratio"}},
        {"NeuralRendering.TransferStrength", double{1.0}, 0, 2, {}},
        {"NeuralRendering.ColourStrength", double{1.0}, 0, 2, {}},
        {"NeuralRendering.MaxRatio", double{2.0}, 1, 16, {}},
        {"NeuralRendering.WhitePoint", double{1.0}, 0.001, 10000, {}},
        {"NeuralRendering.ColourEncoding", Choice{"Auto"}, 0, 2, {"Auto","Linear","SRGB"}},
        {"Compatibility.ENB", Choice{"Auto"}, 0, 2, {"Auto","On","Off"}},
        {"Compatibility.ReShade", Choice{"Auto"}, 0, 2, {"Auto","On","Off"}},
        {"Compatibility.ReShadePlacement", Choice{"AfterSR"}, 0, 2, {"AfterSR","BeforeSR"}},
        {"Compatibility.PublishDepthToReShade", true, 0, 2, {}},
        {"Compatibility.OtherTemporalUpscaler", Choice{"Reject"}, 0, 2, {"Reject"}},
        {"Presentation.VSync", Choice{"Auto"}, 0, 2, {"Auto","On","Off"}},
        {"Presentation.DisplayedFPSLimit", std::int64_t{0}, 0, 1000, {}},
        {"Presentation.Pacing", Choice{"Auto"}, 0, 2, {"Auto","Off"}},
        {"Interface.Enabled", true, 0, 2, {}},
        {"Interface.ToggleMenuKey", Text{"End"}, 0, 2, {}},
        {"Interface.ToggleFrameGenerationKey", Text{"NumMultiply"}, 0, 2, {}},
        {"Interface.ToggleNeuralRenderingKey", Text{"NumSubtract"}, 0, 2, {}},
        {"Interface.ShowRequestedAndEffective", true, 0, 2, {}},
        {"Interface.ShowDisabledOptionReasons", true, 0, 2, {}},
        {"Interface.FontScale", double{1.0}, 0.5, 4, {}},
        {"Diagnostics.Overlay", false, 0, 2, {}},
        {"Diagnostics.CaptureHotkey", Choice{"Off"}, 0, 2, {"Off","CtrlShiftF10"}},
        {"Diagnostics.GPUStageTimings", false, 0, 2, {}},
        {"Diagnostics.DumpCapabilitiesAtStartup", true, 0, 2, {}},
        {"Diagnostics.LogResourceGenerations", false, 0, 2, {}},
        {"Diagnostics.GraphicsDebugValidation", false, 0, 2, {}},
        {"Diagnostics.ProbeReducedWorld", false, 0, 2, {}},
        {"Diagnostics.SpatialBaselineOnly", false, 0, 2, {}},
        {"Patching.EnableVersionedPatches", true, 0, 2, {}},
        {"Patching.ExperimentalPatches", false, 0, 2, {}},
        {"Patching.DisabledPatchIds", Text{""}, 0, 2, {}},
        {"Patching.LogPatchDecisions", true, 0, 2, {}},
    };
    return fields;
}
}
