include(FetchContent)
file(READ "${PROJECT_SOURCE_DIR}/runtime/dependencies.lock.json" RK_DEPENDENCIES)
function(rk_dependency name)
  string(JSON repo GET "${RK_DEPENDENCIES}" sources ${name} repository)
  string(JSON commit GET "${RK_DEPENDENCIES}" sources ${name} commit)
  FetchContent_Declare(${name} GIT_REPOSITORY "${repo}" GIT_TAG "${commit}" ${ARGN})
  FetchContent_MakeAvailable(${name})
  FetchContent_GetProperties(${name} SOURCE_DIR dependency_source)
  set(${name}_SOURCE_DIR "${dependency_source}" PARENT_SCOPE)
endfunction()
set(FMT_TEST OFF CACHE BOOL "" FORCE)
set(SPDLOG_FMT_EXTERNAL ON CACHE BOOL "" FORCE)
rk_dependency(fmt OVERRIDE_FIND_PACKAGE)
rk_dependency(spdlog OVERRIDE_FIND_PACKAGE)
rk_dependency(commonlib SOURCE_SUBDIR rk-headers-only)
rk_dependency(rapidcsv SOURCE_SUBDIR rk-headers-only)
set(ZYDIS_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(ZYDIS_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ZYDIS_BUILD_DOXYGEN OFF CACHE BOOL "" FORCE)
rk_dependency(zydis)
rk_dependency(imgui SOURCE_SUBDIR rk-headers-only)
if(BUILD_TESTING)
  rk_dependency(catch2)
endif()
